[package]
authors = ["Austin Hellyer <hello@austinhellyer.me>"]
build = "build.rs"
name = "nanobot"
version = "0.1.0"

[build-dependencies]
diesel_codegen_syntex = { version = "0.7", features = ["postgres"], optional = true }
dotenv_codegen = { version = "0.9", optional = true }
syntex = { version = "0.38", optional = true }

[dependencies]
chrono = "0.2"
diesel_codegen = { version = "0.7", features = ["postgres"], optional = true }
diesel = "0.7.0"
discord = { git = "https://github.com/SpaceManiac/discord-rs.git" }
dotenv_macros = { version = "0.9", optional = true }
dotenv = "0.8"
env_logger = "0.3"
forecast_io = "0.1"
hummingbird = "0.1"
hyper = "> 0.8"
log = "0.3"
rand = "0.3"
regex = "0.1"
rusqlite = "0.7"
serde_json = "0.8"
serde_macros = "0.8"
serde = "0.8"
urbandictionary = "0.1"
walkdir = "0.1"

[features]
default = ["nightly"]
nightly = ["diesel/unstable", "diesel_codegen", "dotenv_macros"]
with-syntex = ["diesel_codegen_syntex", "dotenv_codegen", "syntex"]

[[bin]]
doc = true
name = "nanobot"
path = "./src/main.rs"

[[bin]]
doc = false
name = "get-channel-history"
path = "./bin/get_channel_history.rs"

[[bin]]
doc = false
name = "tags-v1-to-v2"
path = "./bin/tags_v1_to_v2.rs"
